### ISSUE TITLE
News about opam version

### ISSUE THREAD

**Issue by Karmaki** [ahrefs/jsonschema2atd#6]
Hi,

This looks like a nice project!

Do you think it is already ready to use? I ask that because I haven't found it in `opam`, so I thought that maybe it is not finished (yet?). Do you plan to put it in `opam` some day?

**Comment by Khady** [comment]
Hi @Karmaki. It is already being used in production for us. And there was 2 releases on opam: https://ocaml.org/p/jsonschema2atd/latest

Please let us know if you encounter any problem. The json schema world is kind of crazy, most files don't really follow the spec, and the project is still pretty young, so there might be rough edges.

**Comment by Karmaki** [comment]
Hi @Khady, thank you for your answer. I cannot find it in our `opam` repository, but maybe we are using a local mirror. I need to get information about that. Sure, I let you know if I manage to use it some day. Thanks anyway for this project.
